# Generated by Django 2.2.4 on 2022-09-12 05:20

from django.db import migrations
import phonenumbers


def update_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flat_set = Flat.objects.exclude(owners_phonenumber__isnull=True)
    for flat in flat_set.iterator():
        try:
            phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        except phonenumbers.NumberParseException:
            continue

        if phonenumbers.is_valid_number(phonenumber):
            flat.owner_pure_phone = phonenumbers.format_number(
                phonenumber,
                phonenumbers.PhoneNumberFormat.E164
            )
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20220909_1930'),
    ]

    operations = [
        migrations.RunPython(update_owner_pure_phone)
    ]
