# Generated by Django 2.2.4 on 2022-09-12 11:51

from django.db import migrations
import phonenumbers


def insert_into_owner_from_flat(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')

    flat_set = Flat.objects.all()
    for flat in flat_set.iterator():
        Owner.objects.get_or_create(
            fullname=flat.owner,
            phonenumber=flat.owners_phonenumber, 
            pure_phone=flat.owner_pure_phone
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(insert_into_owner_from_flat)
    ]
